### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by shadesoflight** [messageoftheday/scripts#1]
Hi,

I noticed that ["linux is not currently supported"](https://github.com/messageoftheday/scripts/blob/master/install.sh#L142)  and would like to help.

Could we use cron?  ~~Also, I only know of /etc/motd -- do you know of user-level MOTD's?~~  Ahh, you cat the ~/.motd in the profile.

Maybe putting the script in ~~runlevel 1~~ runlevel 3 would suffice?

Best Wishes,
Chad

**Comment by shadesoflight** [comment]
Sorry, run level 3 would have the networking support needed, I think?

http://en.wikipedia.org/wiki/Runlevel

**Comment by shadesoflight** [comment]
Dry Prep: https://github.com/messageoftheday/scripts/pull/4

Goal: allow individual commands to be overridden as needed in a linux environment.

**Comment by niftylettuce** [comment]
added thx to @shadesoflight

**Comment by shadesoflight** [comment]
:beers:
